// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkSchedule.Entities
{
    internal partial class EmployeeSkill
    {
        [Key]
        public int EmployeeSkillID { get; set; }
        public int EmployeeID { get; set; }
        public int SkillID { get; set; }
        /// <summary>
        /// Levels may be 1=Novice, 2=Proficient, 3=Expert
        /// </summary>
        public int Level { get; set; }
        public int? YearsOfExperience { get; set; }
        [Column(TypeName = "money")]
        public decimal HourlyWage { get; set; }

        [ForeignKey("EmployeeID")]
        /*[InverseProperty("Employee")]*/
        public virtual Employee Employee { get; set; }
        [ForeignKey("SkillID")]
        [InverseProperty("EmployeeSkills")]
        public virtual Skill Skill { get; set; }
    }
}