// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkSchedule.Entities
{
    internal partial class PlacementContract
    {
        public PlacementContract()
        {
            Shifts = new HashSet<Shift>();
            Skills = new HashSet<Skill>();
        }

        [Key]
        public int PlacementContractID { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime EndDate { get; set; }
        public int LocationID { get; set; }
        [StringLength(64)]
        public string Title { get; set; }
        [StringLength(256)]
        public string Requirements { get; set; }

        [ForeignKey("LocationID")]
        [InverseProperty("PlacementContracts")]
        public virtual Location Location { get; set; }
        [InverseProperty("PlacementContract")]
        public virtual ICollection<Shift> Shifts { get; set; }

        [ForeignKey("ContractID")]
        [InverseProperty("Contracts")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}