// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorkSchedule.Entities
{
    internal partial class Shift
    {
        public Shift()
        {
            Schedules = new HashSet<Schedule>();
        }

        [Key]
        public int ShiftID { get; set; }
        public int PlacementContractID { get; set; }
        public int DayOfWeek { get; set; }
        public TimeSpan StartTime { get; set; }
        public TimeSpan EndTime { get; set; }
        public byte NumberOfEmployees { get; set; }
        public bool Active { get; set; }
        /// <summary>
        /// Information about required skills, entry location, keycards, etc.
        /// </summary>
        [StringLength(100)]
        public string Notes { get; set; }

        [ForeignKey("PlacementContractID")]
        [InverseProperty("Shifts")]
        public virtual PlacementContract PlacementContract { get; set; }
        [InverseProperty("Shift")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}